Merge Sort Page And Footer
MastanSayyad/Visual-Sort pull request #104
Opened 2024-07-13 18:57 UTC by AkshatPandey-2004

Hey Added Merge Sort Specific Page And Footer And Back to Top scroll animation

Email: akshatpandey26.2004@gmail.com

Label: Bonus

2024-07-13 19:14 UTC, MastanSayyad requested changes
![image](https://github.com/user-attachments/assets/8c03da6d-38e6-4457-89aa-5cb73451ffd4)

Fix this also add margin left

2024-07-13 20:04 UTC, MastanSayyad commented
LGTM! Let's wait till Co-admin review the changes @AkshatPandey-2004

2024-07-13 20:17 UTC, MastanSayyad commented
> Margin changes done

You can raise another PR for other algos by creating new branches

2024-07-14 08:20 UTC, RadhikaMalpani1702 approved these changes

2024-07-14 08:21 UTC, MastanSayyad approved these changes

2024-07-14 08:21 UTC, merged